# Generated by Django 2.2.13 on 2020-07-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
