# Generated by Django 2.2.13 on 2020-07-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='events',
            new_name='content',
        ),
    ]
