# Generated by Django 2.2.13 on 2020-07-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200706_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='start_time',
            new_name='start',
        ),
    ]
