# Generated by Django 2.2.13 on 2020-07-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200706_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='flag',
            new_name='past',
        ),
    ]
