# Generated by Django 2.2.13 on 2020-07-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20200707_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='past',
            new_name='hastime',
        ),
    ]
