# Generated by Django 2.2.13 on 2020-07-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20200707_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='hastime',
            new_name='flag',
        ),
    ]
