# Generated by Django 3.0.7 on 2020-06-08 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200607_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toparticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=0, verbose_name='置顶')),
            ],
        ),
        migrations.AddField(
            model_name='articlepost',
            name='top',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.Toparticle', verbose_name='置顶'),
            preserve_default=False,
        ),
    ]
