# Generated by Django 3.0.7 on 2020-06-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200608_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='top',
            field=models.BooleanField(default=0, verbose_name='置顶'),
        ),
        migrations.DeleteModel(
            name='Toparticle',
        ),
    ]
