# Generated by Django 3.0.7 on 2020-06-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200608_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='top',
            field=models.BooleanField(default=1, verbose_name='置顶'),
        ),
    ]
