# Generated by Django 3.0.7 on 2020-06-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200608_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.URLField(default=0, verbose_name='文章标题图'),
            preserve_default=False,
        ),
    ]
