# Generated by Django 3.0.7 on 2020-06-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200611_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.URLField(verbose_name='文章标题图'),
        ),
    ]
