# Generated by Django 3.0.7 on 2020-06-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200611_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar',
        ),
    ]
